### ISSUE TITLE
Messy code when clicking 'Open Downloads Folder'

### ISSUE THREAD

**Issue by AndromedaMelody** [M2Team/NanaGet#1] opened 2022-06-01 15:59 UTC
APP Version: NanaGet 1.0 (1.0.36.0)
System Version: Windows 11 22H1 (22621.1)
System Language: English

![Screenshot 2022-06-01 235744](https://user-images.githubusercontent.com/57533055/171448157-69113f4b-b090-405b-bb31-2878479c1e7e.png)

**Comment by MouriNaruto** [comment] 2022-06-01 16:02
I will keep track of this issue and try my best to reproduce it.

P.S. I can't reproduce this issue on my device at current.

Kenji Mouri

**Comment by AndromedaMelody** [comment] 2022-07-10 02:04
Today, I clicked 'Open Downloads Folder', and then the area of Xaml Islands was turned into black, finally it exited due to exception.

**Comment by hl2guide** [comment] 2022-07-30 19:46
> I will keep track of this issue and try my best to reproduce it.
> 
> P.S. I can't reproduce this issue on my device at current.
> 
> Kenji Mouri

![Screenshot 2022-07-31 054525](https://user-images.githubusercontent.com/17044982/181981126-8aaa8796-54af-4cf0-a3c0-9486f4b5ffe4.jpg)

Seems like the download folder is incorrectly set (Japanese?) instead of localized to PC.

I'm using Windows 11 21H2.

**Comment by driver1998** [comment] 2022-08-16 02:09
On my machine, open downloads folder sometimes jumps to c:\windows\system32 instead of the downloads folder. 
19044.1889 here.

**Comment by MouriNaruto** [comment] 2022-08-16 02:24
It looks not the occasionally cases, I will try to fix them by guessing the possible reasons because I can't reproduce.

I will rewrite some implementations in NanaGet because I met some strange application crashes.

Kenji Mouri

**Comment by driver1998** [comment] 2022-08-16 02:49
Looks like the `std::filesystem::path` returned from `NanaGet::GetDownloadsFolderPath` got destructed after c_str(). 

Seems to work fine now if I store the object to a variable.
```diff
diff --git a/NanaGet/MainPage.cpp b/NanaGet/MainPage.cpp
index 8a0a077..bab34cc 100644
--- a/NanaGet/MainPage.cpp
+++ b/NanaGet/MainPage.cpp
@@ -112,11 +112,13 @@ namespace winrt::NanaGet::implementation
     {
         UNREFERENCED_PARAMETER(sender);
         UNREFERENCED_PARAMETER(e);
+
+        std::filesystem::path downloadsFolderPath = NanaGet::GetDownloadsFolderPath();

         SHELLEXECUTEINFOW ExecInfo = { 0 };
         ExecInfo.cbSize = sizeof(SHELLEXECUTEINFOW);
         ExecInfo.lpVerb = L"open";
-        ExecInfo.lpFile = NanaGet::GetDownloadsFolderPath().c_str();
+        ExecInfo.lpFile = downloadsFolderPath.c_str();
         ExecInfo.nShow = SW_SHOWNORMAL;
         ::ShellExecuteExW(&ExecInfo);
     }
```

**Comment by MouriNaruto** [comment] 2022-08-16 04:07
@driver1998 

Thank you. I have merged it just now.

Kenji Mouri

**Closed as completed** 2022-08-16 04:06 UTC
Labels: bug, fixed, archived
